### ISSUE TITLE
Unsupported type warning in chrome for truetype font

### ISSUE THREAD

**Issue by jenbuzz** [GrabarzUndPartner/nuxt-font-loader-strategy#183]
In Chrome there is warning when using ttf extensions with preload.

`<link rel=preload has an unsupported type value`

The `type="font/truetype"` seems invalid.

Can this somehow be overwritten with a valid type or what can be done about this warning?

**Comment by ThornWalli** [comment]
Hi, 

can you try the branch? https://github.com/GrabarzUndPartner/nuxt-font-loader-strategy/tree/feature/fix-ttf-mimetype

The TTF the FontFace type was defined, now the MIME type should fit in the preload.

**Comment by jenbuzz** [comment]
Hey,

Yes, that seems to have solved the problem. I tested it in a setup where both ttf and woff fonts are included and both were correctly loaded; no warnings in Chrome.

Thanks!

**Comment by ThornWalli** [comment]
Package is now up to date
